// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sistema_Gestion_Negocio_ASP.NET_MVC.Context;

#nullable disable

namespace Sistema_Gestion_Negocio_ASP.NET_MVC.Migrations
{
    [DbContext(typeof(NegocioContext))]
    partial class NegocioContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sistema_Gestion_Negocio_ASP.NET_MVC.Models.DetalleVenta", b =>
                {
                    b.Property<string>("IdDetalleVenta")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CantidadProductos")
                        .HasColumnType("int");

                    b.Property<string>("ProductoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Subtotal")
                        .HasColumnType("float");

                    b.Property<string>("VentaId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdDetalleVenta");

                    b.HasIndex("ProductoId");

                    b.HasIndex("VentaId");

                    b.ToTable("Detalle_Ventas", (string)null);
                });

            modelBuilder.Entity("Sistema_Gestion_Negocio_ASP.NET_MVC.Models.FormaPago", b =>
                {
                    b.Property<int>("IdFormaPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFormaPago"), 100L);

                    b.Property<string>("TipoFormaPago")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdFormaPago");

                    b.ToTable("Forma_Pago", (string)null);
                });

            modelBuilder.Entity("Sistema_Gestion_Negocio_ASP.NET_MVC.Models.Negocio", b =>
                {
                    b.Property<Guid>("IdNegocio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RubroId")
                        .HasColumnType("int");

                    b.HasKey("IdNegocio");

                    b.HasIndex("RubroId");

                    b.ToTable("Negocio", (string)null);
                });

            modelBuilder.Entity("Sistema_Gestion_Negocio_ASP.NET_MVC.Models.Producto", b =>
                {
                    b.Property<string>("IdProducto")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("IdProducto");

                    b.HasIndex("NegocioId");

                    b.ToTable("Producto", (string)null);
                });

            modelBuilder.Entity("Sistema_Gestion_Negocio_ASP.NET_MVC.Models.Rubro", b =>
                {
                    b.Property<int>("IdRubro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRubro"), 1000L);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRubro");

                    b.ToTable("Rubro", (string)null);
                });

            modelBuilder.Entity("Sistema_Gestion_Negocio_ASP.NET_MVC.Models.Usuario", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Confirmado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<string>("TokenConfirmacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("NegocioId");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("Sistema_Gestion_Negocio_ASP.NET_MVC.Models.Venta", b =>
                {
                    b.Property<string>("IdVenta")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("FormaPagoId")
                        .HasColumnType("int");

                    b.Property<double>("Total")
                        .HasColumnType("float");

                    b.HasKey("IdVenta");

                    b.HasIndex("FormaPagoId");

                    b.ToTable("Venta", (string)null);
                });

            modelBuilder.Entity("Sistema_Gestion_Negocio_ASP.NET_MVC.Models.DetalleVenta", b =>
                {
                    b.HasOne("Sistema_Gestion_Negocio_ASP.NET_MVC.Models.Producto", "producto")
                        .WithMany("detalleVentas")
                        .HasForeignKey("ProductoId");

                    b.HasOne("Sistema_Gestion_Negocio_ASP.NET_MVC.Models.Venta", "venta")
                        .WithMany("detalleVentas")
                        .HasForeignKey("VentaId");

                    b.Navigation("producto");

                    b.Navigation("venta");
                });

            modelBuilder.Entity("Sistema_Gestion_Negocio_ASP.NET_MVC.Models.Negocio", b =>
                {
                    b.HasOne("Sistema_Gestion_Negocio_ASP.NET_MVC.Models.Rubro", "Rubro")
                        .WithMany("negocios")
                        .HasForeignKey("RubroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rubro");
                });

            modelBuilder.Entity("Sistema_Gestion_Negocio_ASP.NET_MVC.Models.Producto", b =>
                {
                    b.HasOne("Sistema_Gestion_Negocio_ASP.NET_MVC.Models.Negocio", "Negocio")
                        .WithMany("Productos")
                        .HasForeignKey("NegocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Negocio");
                });

            modelBuilder.Entity("Sistema_Gestion_Negocio_ASP.NET_MVC.Models.Usuario", b =>
                {
                    b.HasOne("Sistema_Gestion_Negocio_ASP.NET_MVC.Models.Negocio", "Negocio")
                        .WithMany("Usuarios")
                        .HasForeignKey("NegocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Negocio");
                });

            modelBuilder.Entity("Sistema_Gestion_Negocio_ASP.NET_MVC.Models.Venta", b =>
                {
                    b.HasOne("Sistema_Gestion_Negocio_ASP.NET_MVC.Models.FormaPago", "FormaPago")
                        .WithMany("ventas")
                        .HasForeignKey("FormaPagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormaPago");
                });

            modelBuilder.Entity("Sistema_Gestion_Negocio_ASP.NET_MVC.Models.FormaPago", b =>
                {
                    b.Navigation("ventas");
                });

            modelBuilder.Entity("Sistema_Gestion_Negocio_ASP.NET_MVC.Models.Negocio", b =>
                {
                    b.Navigation("Productos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Sistema_Gestion_Negocio_ASP.NET_MVC.Models.Producto", b =>
                {
                    b.Navigation("detalleVentas");
                });

            modelBuilder.Entity("Sistema_Gestion_Negocio_ASP.NET_MVC.Models.Rubro", b =>
                {
                    b.Navigation("negocios");
                });

            modelBuilder.Entity("Sistema_Gestion_Negocio_ASP.NET_MVC.Models.Venta", b =>
                {
                    b.Navigation("detalleVentas");
                });
#pragma warning restore 612, 618
        }
    }
}
